#!/bin/bash
# One-time, run by hand. Creates an Entra ID App Registration + Service
# Principal for GitHub Actions, with OIDC federated credentials — no
# client secret is ever created or stored.
#
# EDIT the three variables below before running.
#
# Usage: ./02-create-oidc-identity.sh
set -euo pipefail

GITHUB_ORG="<your-github-username-or-org>"     # e.g. "jdoe"
GITHUB_REPO="<your-repo-name>"                 # e.g. "15min-blinket"
TARGET_RG="rg-blinket-dev"                     # the RG Terraform will manage day to day
LOCATION="germanywestcentral"
APP_NAME="github-actions-blinket"

echo "Creating the resource group Terraform will manage (Terraform does NOT create this itself — see README for why)"
az group create --name "$TARGET_RG" --location "$LOCATION"

echo "Creating App Registration + Service Principal: $APP_NAME"
APP_ID=$(az ad app create --display-name "$APP_NAME" --query appId -o tsv)
az ad sp create --id "$APP_ID"

echo "Adding federated credential for the main branch (used by 'terraform apply')"
az ad app federated-credential create --id "$APP_ID" --parameters "{
  \"name\": \"github-main-branch\",
  \"issuer\": \"https://token.actions.githubusercontent.com\",
  \"subject\": \"repo:${GITHUB_ORG}/${GITHUB_REPO}:ref:refs/heads/main\",
  \"audiences\": [\"api://AzureADTokenExchange\"]
}"

echo "Adding federated credential for pull requests (used by 'terraform plan')"
az ad app federated-credential create --id "$APP_ID" --parameters "{
  \"name\": \"github-pull-requests\",
  \"issuer\": \"https://token.actions.githubusercontent.com\",
  \"subject\": \"repo:${GITHUB_ORG}/${GITHUB_REPO}:pull_request\",
  \"audiences\": [\"api://AzureADTokenExchange\"]
}"

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)

echo "Granting Contributor on '$TARGET_RG' only (not the whole subscription)"
az role assignment create \
  --assignee "$APP_ID" \
  --role "Contributor" \
  --scope "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${TARGET_RG}"

cat <<EOF

=============================================================
Save these as GitHub repo VARIABLES (Settings > Secrets and
variables > Actions > Variables tab — these are NOT secrets,
they're identifiers; the trust relationship is what protects you):

  AZURE_CLIENT_ID=$APP_ID
  AZURE_TENANT_ID=$TENANT_ID
  AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
  TARGET_RESOURCE_GROUP=$TARGET_RG

The ONE real secret in this project (Settings > Secrets and
variables > Actions > Secrets tab, scoped to the 'dev' Environment,
not a plain repo secret) is the MySQL admin password — set that
yourself, it isn't generated by this script:

  MYSQL_ADMIN_PASSWORD=<choose a strong password>
=============================================================
EOF
